pipeline {
    agent {
        kubernetes {
            yamlFile '.ci/pod.yaml'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Yogeshwaran-Palanisamy/docker-images']])
            }
        }
        stage('Docker login') {
            steps {
               withCredentials([usernamePassword(credentialsId: 'docker-credentials',
                                  usernameVariable: 'username', 
                                  passwordVariable: 'password')]) {
                    sh 'docker login -u $username -p $password'
}
            }
        }
        stage('Docker build') {
            steps {
               sh 'docker build -t helm3:latest .'
            }
        }
        stage('Docker push') {
            steps {
                sh 'docker push helm3:latest'   
            }
        }
    }
}